sudo: required
services:
  - docker
before_install:
    - bash build.sh
script:
    - sh test.sh
after_success:
    - docker images
deploy:
    - provider: script
      script: bash docker_push.sh
      on:
        tags: true
