sudo: required
services:
  - docker
before_install:
    - docker pull klabteam/base
    - cd base/klab
    - docker build -t klabteam/klab .
script:
    - cd ../..
    - sh test.sh
after_success:
    - docker images
deploy:
    - provider: script
      script: bash docker_push.sh master
      on:
        branch: master
    - provider: script
      script: bash docker_push.sh
      on:
        tags: true
