sudo: required
services:
    - docker
before_install:
    - sudo useradd -u 1000 kesci
    - sudo chown -R kesci test/
    - bash build.sh
script:
    - sh test.sh
after_success:
    - docker images
deploy:
    - provider: script
      script: bash docker_push.sh tags
      on:
        tags: true
    - provider: script
      script: bash docker_push.sh master
      on:
        branch: master
    - provider: script
      script: bash docker_push.sh gpu
      on:
        branch: gpu-master
